# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
production:
 database: db/production.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: challenge_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: challenge_test
  pool: 5
  username: 
  password:
