# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42cdbcc2e9b0baaff9491c9c00cb4cb2f9f3ea823781746eac4c813edc8ac2f12ed1bda3747f20d856cbec894c7711b60c73cbc5688ab585b7d6c6b65e379457

test:
  secret_key_base: 9f72a59e172ac2d20ae7062a020a821f5e1b3e1d2305ab616269f24bf3c4d12a269ee213cc5c5ce59b841a350c06f56c98ccccb7c4f5f18eebbac21bab2ef212

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
